### ISSUE TITLE
Is this still maintained? What to use instead ? 

### ISSUE THREAD

**Issue by Simon-Kaz** [TwitchLib/TwitchLib.Extension#9]
Hello, is this still maintained? Seems like there haven't been any updates in a long time. 

Are there any viable alternatives to handle twitch extension API in c#?

**Comment by LuckyNoS7evin** [comment]
Although this hasn’t changed in a long time neither has the API. As far as I know this is still the best option for the extensions API

**Comment by Simon-Kaz** [comment]
Sweet, i'll give it a shot! thanks @LuckyNoS7evin
